name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check for tests
        id: check_tests
        run: |
          if [ $(find . -name 'test*.py' | wc -l) -gt 0 ]; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        if: steps.check_tests.outputs.has_tests == 'true'
        run: python -m unittest discover

      - name: No tests found
        if: steps.check_tests.outputs.has_tests != 'true'
        run: echo "No tests found, skipping test run"