name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
        
    - name: Lint with flake8
      run: |
        flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run unit tests
      run: |
        pytest tests/unit -v --cov=src
        
    - name: Run integration tests
      run: |
        pytest tests/integration -v
        
    - name: Run hardware simulation tests
      run: |
        python -m src.core.testing.ci_pipeline --config ci_config.json --test-type hardware
        
    - name: Upload test results
      uses: actions/upload-artifact@8f2cf3c87b382d556d6d1ea7a5e4e7d8c3c3fea5 # v3.1.3
      with:
        name: test-results
        path: test_results/

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser
        pip install -e ".[docs]"
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Upload documentation artifact
      uses: actions/upload-artifact@8f2cf3c87b382d556d6d1ea7a5e4e7d8c3c3fea5 # v3.1.3
      with:
        name: documentation
        path: docs/_build/html
        retention-days: 7