name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U sphinx==7.2.6 sphinx-rtd-theme
        pip install -U "myst-parser==1.0.0"
        pip install -e .
        pip list
    - name: Debug environment
      run: |
        echo "Python version:"
        python --version
        echo "Pip packages:"
        pip list
        echo "Working directory:"
        pwd
        ls -la docs/
    - name: Build documentation
      run: |
        cd docs
        make html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html